name: Build & Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: "2 days"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install & build
        run: |
          npm ci
          npm run build
      - name: Upload public dir
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public
        env:
          CI: true
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download public dir
        uses: actions/download-artifact@v4
        with:
          name: public
      - name: Upload to MU via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "public/"
          server-dir: "httpdocs/minisite/"
